import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

interface POItem { description: string; quantity: number; unit_price: number; unit: string }

interface PurchaseOrder {
  po_number:     string
  status:        string
  items:         POItem[]
  subtotal:      number
  vat_amount:    number
  total_amount:  number
  payment_terms: string | null
  delivery_date: string | null
  notes:         string | null
  created_at:    string
  purchase_requests?: { request_number: string } | null
}

interface Vendor { name: string; voen: string | null }

function money(n: number) {
  return '₼ ' + n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
}

function fmtDate(d: string) {
  return new Date(d).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
}

export async function generatePOPDF(po: PurchaseOrder, vendor: Vendor | null) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  const BG   = [15, 40, 90] as [number, number, number]
  const BLUE = [37, 99, 235] as [number, number, number]
  const W    = 210
  const M    = 14

  // Header band
  doc.setFillColor(...BG)
  doc.rect(0, 0, W, 38, 'F')

  // Logo text
  doc.setFontSize(20).setFont('helvetica', 'bold').setTextColor(255, 255, 255)
  doc.text('Az', M, 16)
  doc.setTextColor(147, 197, 253)
  doc.text('Finance', M + 11, 16)

  // PO Number & status
  doc.setFontSize(11).setFont('helvetica', 'bold').setTextColor(255, 255, 255)
  doc.text('PURCHASE ORDER', W - M, 12, { align: 'right' })
  doc.setFontSize(16)
  doc.text(po.po_number, W - M, 20, { align: 'right' })
  doc.setFontSize(9).setFont('helvetica', 'normal').setTextColor(147, 197, 253)
  doc.text(po.status.toUpperCase(), W - M, 27, { align: 'right' })

  // Meta info
  let y = 48
  doc.setFontSize(9).setFont('helvetica', 'normal').setTextColor(80, 80, 80)

  const left  = [[`Date:`,       fmtDate(po.created_at)],
                  [`Delivery:`,  po.delivery_date ? fmtDate(po.delivery_date) : '—'],
                  [`Payment:`,   po.payment_terms ?? '—']]
  const right: string[][] = [
    [`Vendor:`, vendor?.name ?? '—'],
    [`VÖEN:`,   vendor?.voen ?? '—'],
    ...(po.purchase_requests ? [[`PR:`, po.purchase_requests.request_number]] : []),
  ]

  left.forEach(([label, value], i) => {
    doc.setFont('helvetica', 'bold').text(label, M, y + i * 6)
    doc.setFont('helvetica', 'normal').text(value, M + 22, y + i * 6)
  })
  right.forEach(([label, value], i) => {
    doc.setFont('helvetica', 'bold').text(label, W / 2 + 10, y + i * 6)
    doc.setFont('helvetica', 'normal').text(value, W / 2 + 28, y + i * 6)
  })

  y += 24

  // Line items table
  autoTable(doc, {
    startY: y,
    head:   [['#', 'Description', 'Unit', 'Qty', 'Unit Price', 'Total']],
    body:   po.items.map((it, i) => [
      i + 1,
      it.description,
      it.unit,
      it.quantity,
      money(it.unit_price),
      money(it.quantity * it.unit_price),
    ]),
    headStyles: { fillColor: BLUE, textColor: [255, 255, 255], fontSize: 8, fontStyle: 'bold' },
    bodyStyles: { fontSize: 8 },
    columnStyles: {
      0: { cellWidth: 8 },
      2: { cellWidth: 18 },
      3: { cellWidth: 14, halign: 'center' },
      4: { cellWidth: 26, halign: 'right' },
      5: { cellWidth: 28, halign: 'right' },
    },
    margin: { left: M, right: M },
    alternateRowStyles: { fillColor: [248, 250, 252] },
  })

  // Totals
  const finalY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6
  const tx = W - M - 60

  const totals = [
    ['Subtotal:', money(po.subtotal)],
    ...(po.vat_amount > 0 ? [['VAT (18%):', money(po.vat_amount)]] : []),
    ['TOTAL:', money(po.total_amount)],
  ]

  totals.forEach(([label, value], i) => {
    const isTotal = label === 'TOTAL:'
    const ty      = finalY + i * 7
    if (isTotal) { doc.setFillColor(248, 250, 252); doc.rect(tx - 2, ty - 4, 62, 8, 'F') }
    doc.setFontSize(isTotal ? 10 : 9)
       .setFont('helvetica', isTotal ? 'bold' : 'normal')
       .setTextColor(isTotal ? 15 : 80, isTotal ? 40 : 80, isTotal ? 90 : 80)
    doc.text(label, tx, ty)
    doc.text(value, W - M, ty, { align: 'right' })
  })

  // Notes
  if (po.notes) {
    const ny = finalY + totals.length * 7 + 10
    doc.setFontSize(8).setFont('helvetica', 'bold').setTextColor(80, 80, 80)
    doc.text('Notes:', M, ny)
    doc.setFont('helvetica', 'normal')
    doc.text(po.notes, M, ny + 5, { maxWidth: W - M * 2 })
  }

  // Footer
  doc.setFontSize(7).setTextColor(160, 160, 160).setFont('helvetica', 'normal')
  doc.text(`Generated by AzFinance · ${new Date().toLocaleDateString('en-GB')}`, W / 2, 290, { align: 'center' })

  doc.save(`${po.po_number}.pdf`)
}
